coverage:
  status:
    project:
      default:
        # Do not fail PRs if the code coverage drops.
        target: 0%
        threshold: 100%
        if_ci_failed: success
        informational: true

ignore:
  - "**/*.yaml"
  - "**/*.yml"

