name: "Build package and run multiple tests"

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: ubuntu-latest
          path: ~/.cache/pip
        - os: macos-latest
          path: ~/Library/Caches/pip
        - os: windows-latest
          path: ~\AppData\Local\pip\Cache
        python-version: [ 3.7, 3.8, 3.9, '3.10' ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - uses: actions/cache@v2
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements_dev.txt') }}
      - name: Install dependencies
        run: |
            python -m pip install wheel pytest pytest-cov codecov pandas pyxlsb types-setuptools
            pip install -r requirements_dev.txt
      - name: Build wheels
        run: pip wheel -w DEST_DIR .
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value
      - name: Run tests with pytest, mypy, coverage, bandit and restructuredtext check
        run: |
            py.test -rP --cov=./pylexique/
            codecov --token=370386ee-28d7-441f-b4eb-7f63f8c5c3e9
            bandit -r pylexique/
            mypy --strict --ignore-missing-imports --show-error-codes pylexique/


